- New data type "pktsrc", enabling access to packets. Currently implemented are pcap-offline and pcap-live:
    local ref<pktsrc<Hilti::PktSrc::PcapOffline>> psrc
    local tuple<double,ref<bytes>> pkt

    psrc = new pktsrc<Hilti::PktSrc::PcapOffline> "trace.pcap"
    
    @loop:
        pkt = pktsrc.read psrc
        call Hilti::print (pkt)
        jump @loop

    (That will abort with an exception once the trace file is
    exhausted.)

- New overloaded operators "begin" and "end", returning
  corresponding iterators for containers and similar types (incl.
  packet sources). Older types which so far has "begin" and "end"
  methods have been adapted accordingly. (The latter makes the diff
  pretty large.)
  
- Bugfixes.

diff --git a/hilti/tools/hilti-config/hilti-config b/hilti/tools/hilti-config/hilti-config
--- a/hilti/tools/hilti-config/hilti-config
+++ b/hilti/tools/hilti-config/hilti-config
@@ -51,6 +51,18 @@ if [ ! -d "$base/libhilti" ]; then
     exit 1
 fi
 
+### Add the libpcap flags
+
+which -s pcap-config
+
+if [ $? == 1 ]; then
+   echo "cannot find pcap-config"
+   exit 1
+fi 
+
+pcap_cflags=`pcap-config --cflags `
+pcap_libs=`pcap-config --libs | sed 's/-L /-L/g'` # clang doesn't like spaces.
+
 ### Parse command line.
 
 if [ "$#" == "0" ]; then 
@@ -82,7 +94,7 @@ while [ "$1" != "" ]; do
             shift;;
             
         --libs-c)
-            echo "-lc -lpthread"
+            echo "-lc -lpthread $pcap_libs"
             shift;;
             
         --hilticflags)
@@ -94,11 +106,11 @@ while [ "$1" != "" ]; do
             shift;;
             
         --cflags)
-            echo "-I$base/libhilti"
+            echo "-I$base/libhilti $pcap_cflags"
             shift;;
             
         --cxxflags)
-            echo "-I$base/libhilti"
+            echo "-I$base/libhilti $pcap_cflags"
             shift;;
             
         --libhilti)
